# output "cluster_endpoint" {
#   description = "Endpoint for EKS control plane."
#   value       = module.eks.cluster_endpoint
# }

# output "cluster_security_group_id" {
#   description = "Security group ids attached to the cluster control plane."
#   value       = module.eks.cluster_security_group_id
# }

# output "kubectl_config" {
#   description = "kubectl config as generated by the module."
#   value       = module.eks.kubeconfig
# }

# output "config_map_aws_auth" {
#   description = "A kubernetes configuration to authenticate to this EKS cluster."
#   value       = module.eks.config_map_aws_auth
# }

# output "s3_terraform_remote_state_config" {
#     description = "provisioning s3 config"
#     value = [
#         aws_s3_bucket.terraform_state.bucket,
#         aws_s3_bucket.terraform_state.bucket_domain_name,
#         aws_s3_bucket.terraform_state.bucket_regional_domain_name
#     ]
# }


output "aws_vpc_name" {
  description = "AWS VPC Name."
  value       = module.vpc.name
}

output "region" {
  description = "AWS region."
  value       = var.region
}


output "aws_availability_zones" {
  description = "AWS Availability Zones"
  value       = data.aws_availability_zones.available.names
}

output "provision_environment" {
  description = "provision environment"
  value       = var.environment
}



output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

